# Generated by Django 2.0.3 on 2018-03-23 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gist_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gist',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gist',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 19, 38, 46, 746560)),
        ),
    ]
